# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180222_1717'),
        ('coursefavs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
    ]
