# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180222_1717'),
        ('coursefavs', '0002_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorite',
            field=models.ManyToManyField(related_name='upvote', to='login.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='login.User'),
        ),
    ]
