# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursefavs', '0003_auto_20180228_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
