# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursefavs', '0006_auto_20180228_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_added',
        ),
    ]
