# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180222_1717'),
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ManyToManyField(related_name='admin', to='login.User'),
        ),
    ]
